apiVersion: apps/v1
kind: Deployment
metadata:
  name: twtbot
  labels:
    app: twtbot
    owner: thewebteam
    env: {{CIRCLE_BRANCH}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twtbot
  template:
    metadata:
      labels:
        app: twtbot
        commitHash: "{{CIRCLE_SHA1}}"
        buildNumber: "{{CIRCLE_BUILD_NUM}}"
        env: "{{CIRCLE_BRANCH}}"
    spec:
      dnsConfig:
        options:
          - name: single-request
      imagePullSecrets:
        - name: twt-registry
      containers:
        - name: server
          image: registry.digitalocean.com/twt-registry/twtbot:{{CIRCLE_SHA1}}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: "twtbot-secrets"

